# Important: YAML files are indentation sensitive. Do NOT change the indentation of the templates provided All indentations are in increments of 2 spaces.
# YAML files require all field values to be in lowercase, can include numbers
apiVersion: apps/v1
#Specifies the kind of resource we are creating
kind: Deployment
#Metadata to identify the deployment in the cluster
metadata:
  name: #fill-this

#Specifications of the deployment
spec:
  #The number of replicas the deployment must have
  replicas: #fill this

  #Metadata to identify the replicaset in the cluster
  selector:
    matchLabels:
      app: #fill-this
  template:
    metadata:
      labels:
        app: #fill-this

    # Pod specs
    spec:
      containers:
      - name: #fill-this
        image: #fill-this
        resources:
          limits:
            memory: "fill-this"
            cpu: "#fill-this"
        ports:
        - containerPort: #fill-this

# This divider is a YAML specification to seperate different YAML scripts in the same file
---

apiVersion: v1
#Specifies the kind of resource we are creating
kind: Service
metadata:
  name: #fill-this
spec:
# This selector is IMPORTANT, it selects those pods in the deployment that match the below key-value pair
# Only those pods that match get traffic from the service
  selector:
    app: #fill-this
  ports:
  # The type of protocol the service exposes
    - protocol: #fill-this

  # What is the port the SERVICE must expose(This field is not needed for NodePort services)
      port: #fill-this

  # What is the port that the POD EXPOSES 
      targetPort: #fill-this

# The type of service we are creating
  type: #fill-this